#!/bin/bash
# QUICK_START.sh - One-line commands to get started with Telegram fetcher

echo "╔════════════════════════════════════════════════════════════╗"
echo "║      EMILIA TELEGRAM PROXY FETCHER - QUICK START          ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "Choose an option:"
echo ""
echo "1️⃣  Complete Workflow (Fetch → Merge → Scan)"
echo "   ./fetch_and_scan.sh"
echo ""
echo "2️⃣  Fetch Only from Telegram"
echo "   ./emilia -fetch zip_cm_edu_kg"
echo ""
echo "3️⃣  Scan Existing Proxies"
echo "   ./emilia -input Data/proxy-rabu-16-agustus.txt"
echo ""
echo "4️⃣  Run Demo Test"
echo "   ./demo_test.sh"
echo ""
echo "5️⃣  Build from Source"
echo "   go build -o emilia ."
echo ""
echo "───────────────────────────────────────────────────────────"
echo "📚 Documentation:"
echo "   • TELEGRAM_FETCH_GUIDE.md      (Complete usage guide)"
echo "   • IMPLEMENTATION_SUMMARY.md    (Technical details)"
echo "   • FINAL_HANDOFF_REPORT.md      (Full report)"
echo "   • README.md                    (Project overview)"
echo ""
echo "🔧 Configuration Required:"
echo "   • Create .env with: WORKER_URLS=https://url1,https://url2"
echo "   • Or use keys.json with WORKER_URLS field"
echo ""
echo "✅ Status: Production Ready"
echo "───────────────────────────────────────────────────────────"
